name: Zip Folder or File

on: workflow_dispatch

jobs:
  zipper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: ZIPPER
        uses: "TaiStudio/Zipper@master"
        with:
          ZIPPER_IN: "./node_modules"
          ZIPPER_OUT: "./node_modules"
          ZIPPER_EXT: ".zip"
      - name: GITHUB RELEASE
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Zipper Done"
          files: |
            *.zip
            *.tar